"""Closed-profile validation: a conformant entviz contains ONLY the enumerated
channels — there is no slot for a brand/logo, a copyright mark, or any extra
text or graphic overlaid on the diagram. Purely non-rendering advisory metadata
(<title>/<desc>/<metadata>/comments/extra data-*) is allowed; it adds no ink.

These tests pin both directions: every clean render passes, and each class of
overlay (a logo image, a copyright text, stray text, an extra shape, a wrapping
link, an injected <style>/<script>) is rejected.
"""
import pytest
from lxml import etree

from compliance import validate_closed_profile
from entviz.pipeline import render

SVG = "{http://www.w3.org/2000/svg}"

CLEAN_INPUTS = [
    "deadbeef",                       # tiny
    "5493001KJTIIGC8Y1R12",           # LEI: has a suffix
    "a" * 66,                         # blank-cell map + ellipse
    "The quick brown fox jumps",      # base64url fallback
]


@pytest.mark.parametrize("inp", CLEAN_INPUTS)
def test_clean_entviz_has_no_profile_violations(inp):
    assert validate_closed_profile(render(inp)) == []


def test_clean_entviz_with_note_passes():
    assert validate_closed_profile(render("deadbeef", note="git")) == []


def _mutate(build):
    base = render("5493001KJTIIGC8Y1R12", note="git")
    root = etree.fromstring(base.encode())
    build(root)
    return etree.tostring(root, encoding="unicode")


def _logo_image(r):
    e = etree.SubElement(r, SVG + "image")
    e.set("href", "logo.png"); e.set("x", "20"); e.set("y", "20")
    e.set("width", "40"); e.set("height", "40")


def _extra_background_rect(r):
    e = etree.SubElement(r, SVG + "rect")
    e.set("x", "0"); e.set("y", "0"); e.set("width", "20"); e.set("height", "20")
    e.set("fill", "#ff00ff")


def _copyright_text(r):
    t = etree.SubElement(r, SVG + "text")
    t.set("x", "4"); t.set("y", "10"); t.text = "(c) ACME"


def _text_in_grid(r):
    g = next(x for x in r.iter(SVG + "g") if x.get("data-channel") == "grid")
    etree.SubElement(g, SVG + "text").text = "hi"


def _extra_text_in_cell(r):
    c = next(x for x in r.iter(SVG + "g") if x.get("data-channel") == "cell")
    etree.SubElement(c, SVG + "text").text = "x"


def _link_wrapper(r):
    etree.SubElement(r, SVG + "a").set("href", "http://evil.example")


def _style_block(r):
    etree.SubElement(r, SVG + "style").text = "rect{fill:red}"


def _script_block(r):
    etree.SubElement(r, SVG + "script").text = "alert(1)"


def _use_logo(r):
    etree.SubElement(r, SVG + "use").set("href", "#brand")


@pytest.mark.parametrize("build", [
    _logo_image, _extra_background_rect, _copyright_text, _text_in_grid,
    _extra_text_in_cell, _link_wrapper, _style_block, _script_block, _use_logo,
])
def test_overlaid_content_is_rejected(build):
    violations = validate_closed_profile(_mutate(build))
    assert violations, "expected the overlay to be rejected as a profile violation"


def test_advisory_metadata_is_allowed():
    def build(r):
        etree.SubElement(r, SVG + "desc").text = "an entviz"
        etree.SubElement(r, SVG + "title").text = "fingerprint"
        r.insert(0, etree.Comment(" generated by entviz "))
        r.set("data-vendor", "ok")  # extra non-rendering attribute
    assert validate_closed_profile(_mutate(build)) == []
